./os os_0_mlq_paging  > output/os_0_mlq_paging.output
./os os_1_mlq_paging > output/os_1_mlq_paging.output
./os os_1_mlq_paging_small_1K > output/os_1_mlq_paging_small_1K.output
./os os_1_mlq_paging_small_4K > output/os_1_mlq_paging_small_4K.output
./os os_1_singleCPU_mlq > output/os_1_singleCPU_mlq.output
./os os_1_singleCPU_mlq_paging > output/os_1_singleCPU_mlq_paging.output
./os sched > output/sched.output
./os sched_0 > output/sched_0.output
./os sched_1 > output/sched_1.output
./os os_sc > output/os_sc.output
./os os_syscall > output/os_syscall.output
./os os_syscall_list > output/os_syscall_list.output
./os os_kmem > output/os_kmem.output
