#ifndef MM64_H
#define MM64_H

#include "mm.h"
#define MM64_BITS_PER_LONG 64

#define PAGING64_CPU_BUS_WIDTH 57 /* 57 bit bus - MAX SPACE 4MB */
#define PAGING64_PAGESZ  4096      /* 4KB or 12-bits PAGE NUMBER */

#define GENMASK64(h, l) \
	(((~0ULL) << (l)) & (~0ULL >> (MM64_BITS_PER_LONG  - (h) - 1)))

#define PAGING64_MAX_PGN  (DIV_ROUND_UP(BIT_ULL(21),PAGING64_PAGESZ))
#define PAGING64_PAGE_ALIGNSZ(sz) (DIV_ROUND_UP(sz,PAGING64_PAGESZ)*PAGING64_PAGESZ)
#define PAGING64_LEVEL_BITS 9
#define PAGING64_LEVEL_ENTRIES (1ULL << PAGING64_LEVEL_BITS)


/* OFFSET */
#define PAGING64_ADDR_OFFST_HIBIT 11
#define PAGING64_ADDR_OFFST_LOBIT 0

/* PT */
#define PAGING64_ADDR_PT_HIBIT 20
#define PAGING64_ADDR_PT_LOBIT 12
#define PAGING64_ADDR_PT_SHIFT 12

/* PMD */
#define PAGING64_ADDR_PMD_HIBIT 29
#define PAGING64_ADDR_PMD_LOBIT 21

/* PUD */
#define PAGING64_ADDR_PUD_HIBIT 38
#define PAGING64_ADDR_PUD_LOBIT 30

/* P4D */
#define PAGING64_ADDR_P4D_HIBIT 47
#define PAGING64_ADDR_P4D_LOBIT 39

/* PGD */
#define PAGING64_ADDR_PGD_HIBIT 56
#define PAGING64_ADDR_PGD_LOBIT 48

/* Extract PGD Entry */
#define PAGING64_ADDR_OFFST(addr) GETVAL(addr,PAGING64_ADDR_OFFST_MASK,PAGING64_ADDR_OFFST_LOBIT)
#define PAGING64_ADDR_PT(addr)   ((addr&PAGING64_ADDR_PT_MASK)>>PAGING64_ADDR_PT_LOBIT)
//GETVAL(addr,PAGING64_ADDR_PT_MASK,PAGING64_ADDR_PT_LOBIT)
#define PAGING64_ADDR_PMD(addr)   ((addr&PAGING64_ADDR_PMD_MASK)>>PAGING64_ADDR_PMD_LOBIT)
//GETVAL(addr,PAGING64_ADDR_PMD_MASK,PAGING64_ADDR_PMD_LOBIT)
#define PAGING64_ADDR_PUD(addr)   ((addr&PAGING64_ADDR_PUD_MASK)>>PAGING64_ADDR_PUD_LOBIT)
//GETVAL(addr,PAGING64_ADDR_PUD_MASK,PAGING64_ADDR_PUD_LOBIT)
#define PAGING64_ADDR_P4D(addr)   ((addr&PAGING64_ADDR_P4D_MASK)>>PAGING64_ADDR_P4D_LOBIT)
//GETVAL(addr,PAGING64_ADDR_P4D_MASK,PAGING64_ADDR_P4D_LOBIT)
#define PAGING64_ADDR_PGD(addr)   ((addr&PAGING64_ADDR_PGD_MASK)>>PAGING64_ADDR_PGD_LOBIT)
//GETVAL(addr,PAGING64_ADDR_PGD_MASK,PAGING64_ADDR_PGD_LOBIT)


/* Masks */
#define PAGING64_ADDR_OFFST_MASK  GENMASK64(PAGING64_ADDR_OFFST_HIBIT,PAGING64_ADDR_OFFST_LOBIT)
#define PAGING64_ADDR_PT_MASK  GENMASK64(PAGING64_ADDR_PT_HIBIT,PAGING64_ADDR_PT_LOBIT)
#define PAGING64_ADDR_PMD_MASK  GENMASK64(PAGING64_ADDR_PMD_HIBIT,PAGING64_ADDR_PMD_LOBIT)
#define PAGING64_ADDR_PUD_MASK  GENMASK64(PAGING64_ADDR_PUD_HIBIT,PAGING64_ADDR_PUD_LOBIT)
#define PAGING64_ADDR_P4D_MASK  GENMASK64(PAGING64_ADDR_P4D_HIBIT,PAGING64_ADDR_P4D_LOBIT)
#define PAGING64_ADDR_PGD_MASK  GENMASK64(PAGING64_ADDR_PGD_HIBIT,PAGING64_ADDR_PGD_LOBIT)

#define PAGING64_PTE_PRESENT_MASK BIT_ULL(0)
#define PAGING64_PTE_SWAPPED_MASK BIT_ULL(1)
#define PAGING64_PTE_DIRTY_MASK BIT_ULL(2)
#define PAGING64_PTE_SWPTYP_LOBIT 3
#define PAGING64_PTE_SWPTYP_HIBIT 7
#define PAGING64_PTE_FPN_LOBIT 12
#define PAGING64_PTE_FPN_HIBIT 51
#define PAGING64_PTE_SWPOFF_LOBIT 12
#define PAGING64_PTE_SWPOFF_HIBIT 51
#define PAGING64_PTE_SWPTYP_MASK GENMASK64(PAGING64_PTE_SWPTYP_HIBIT,PAGING64_PTE_SWPTYP_LOBIT)
#define PAGING64_PTE_FPN_MASK GENMASK64(PAGING64_PTE_FPN_HIBIT,PAGING64_PTE_FPN_LOBIT)
#define PAGING64_PTE_SWPOFF_MASK GENMASK64(PAGING64_PTE_SWPOFF_HIBIT,PAGING64_PTE_SWPOFF_LOBIT)
#define PAGING64_PAGE_PRESENT(pte) ((pte) & PAGING64_PTE_PRESENT_MASK)
#define PAGING64_PAGE_SWAPPED(pte) ((pte) & PAGING64_PTE_SWAPPED_MASK)
#define PAGING64_PTE_FPN(pte) (((pte) & PAGING64_PTE_FPN_MASK) >> PAGING64_PTE_FPN_LOBIT)
#define PAGING64_PTE_SWP(pte) (((pte) & PAGING64_PTE_SWPOFF_MASK) >> PAGING64_PTE_SWPOFF_LOBIT)
#define PAGING64_PTE_SET_FPN(pte, fpn) ((pte) = ((pte) & ~PAGING64_PTE_FPN_MASK) | (((addr_t)(fpn) << PAGING64_PTE_FPN_LOBIT) & PAGING64_PTE_FPN_MASK))
#define PAGING64_PTE_SET_SWP(pte, swpoff) ((pte) = ((pte) & ~PAGING64_PTE_SWPOFF_MASK) | (((addr_t)(swpoff) << PAGING64_PTE_SWPOFF_LOBIT) & PAGING64_PTE_SWPOFF_MASK))
#define PAGING64_PTE_SET_SWPTYP(pte, swptyp) ((pte) = ((pte) & ~PAGING64_PTE_SWPTYP_MASK) | (((addr_t)(swptyp) << PAGING64_PTE_SWPTYP_LOBIT) & PAGING64_PTE_SWPTYP_MASK))
#define PAGING64_DUMMY_PTE ((addr_t)0xdeadbee0ULL)



#endif
